model:
  path: /app/models/best_model.pth
  input_size: [256, 256]
  
data:
  train_path: /data/train
  val_path: /data/val
  
logging:
  level: INFO
  file: /var/log/pose-classifier.log
  
monitoring:
  prometheus_port: 8000
